version: '3.8'

services:
  # API Servisi
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sesli-sohbet-api:prod
    container_name: sesli-sohbet-api
    restart: always
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=production
      - PORT=9999
      - MONGODB_URI=mongodb://mongodb:27017/sesli-sohbet
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=7d
      - CORS_ORIGIN=${CORS_ORIGIN}
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  # MongoDB Servisi
  mongodb:
    image: mongo:6.0
    container_name: sesli-sohbet-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - mongodb-data:/data/db
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # Redis Servisi
  redis:
    image: redis:7.0-alpine
    container_name: sesli-sohbet-redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - redis-data:/data
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Nginx Servisi
  nginx:
    image: nginx:1.25-alpine
    container_name: sesli-sohbet-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/ssl:/etc/nginx/ssl
      - ./deployment/www:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  sesli-sohbet-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
