FROM node:18

# Gerekli paketleri yükle
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    make \
    g++

# Çalışma dizini oluştur
WORKDIR /app

# Bağımlılıkları kopyala
COPY package*.json ./

# Bağımlılıkları yükle
RUN npm install --build-from-source

# Uygulama kodunu kopyala
COPY . .

# Ortam değişkenleri
ENV NODE_ENV=development
ENV PORT=9999

# Uygulama portunu aç
EXPOSE ${PORT}

# Uygulamayı başlat
CMD ["node", "dist/src/app.js"]
