# Tek Dockerfile (dev ve prod için)
ARG NODE_ENV=production
FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

EXPOSE 9092

CMD ["node", "dist/src/app.js"]
