version: '3.8'

services:
  # API Servisi
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sesli-sohbet-api:latest
    container_name: sesli-sohbet-api
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-9092}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/fisqos}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - NODE_OPTIONS=${NODE_OPTIONS:---max-old-space-size=512}
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-9092}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  # MongoDB Servisi
  mongodb:
    image: mongo:6.0
    container_name: sesli-sohbet-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  # Redis Servisi
  redis:
    image: redis:7.0-alpine
    container_name: sesli-sohbet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # Mediasoup Servisi
  mediasoup:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sesli-sohbet-mediasoup:latest
    container_name: sesli-sohbet-mediasoup
    restart: unless-stopped
    ports:
      - "3002:3002"
      - "10000-10999:10000-10999/udp"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MEDIASOUP_MIN_PORT=10000
      - MEDIASOUP_MAX_PORT=10999
      - NODE_OPTIONS=--max-old-space-size=512
    networks:
      - sesli-sohbet-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

networks:
  sesli-sohbet-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
