services:
  - type: web
    name: sesli-sohbet
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/render-app.js --port=9092
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 9092
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
