services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    image: sesli-sohbet-demo:latest
    container_name: sesli-sohbet-demo
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=development
      - PORT=9999
    networks:
      - demo-network
    command: ["node", "server.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    # Kaynak kullanımını sınırla
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

networks:
  demo-network:
    driver: bridge
